"""discord id link

Revision ID: 0c9e25e82463
Revises: a1148032fd6d
Create Date: 2026-08-13 11:54:15.285000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9e25e82463'
down_revision: Union[str, None] = 'a1148032fd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('discord_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'players', ['discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'discord_id')
    # ### end Alembic commands ###
