"""auth token hash

Revision ID: a08242453b38
Revises: 0c9e25e82463
Create Date: 2026-08-13 12:45:21.288841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08242453b38'
down_revision: Union[str, None] = '0c9e25e82463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('auth_token_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'players', ['auth_token_hash'])
    op.create_unique_constraint(None, 'players', ['discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'auth_token_hash')
    # ### end Alembic commands ###
